import AnimatedText from '@/components/Animated/AnimatedText'
import Layout from '@/Layout'
import { motion, useMotionValue } from 'framer-motion'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRef } from 'react'

const FramerImage = motion(Image)

const MovingImage = ({ title, image, link }) => {
	const x = useMotionValue(0)
	const y = useMotionValue(0)
	const imageRef = useRef(null)
	function handleMouse(event) {
		imageRef.current.style.display = 'inline-block'
		x.set(event.pageX)
		y.set(-10)
	}
	function handleMouseLeave(event) {
		imageRef.current.style.display = 'none'
		x.set(0)
		y.set(0)
	}
	return (
		<Link
			href={link}
			target='_blank'
			onMouseMove={handleMouse}
			onMouseLeave={handleMouseLeave}
		>
			<h2 className='capitalize text-xl font-semibold hover:underline'>
				{title}
			</h2>
			<FramerImage
				whileInView={{ opacity: 1, transition: { duration: 0.2 } }}
				initial={{ opacity: 0 }}
				style={{ x: x, y: y }}
				ref={imageRef}
				src={image}
				alt={title}
				className='z-10 w-96 h-auto hidden absolute rounded-lg'
				priority
				sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw'
			/>
		</Link>
	)
}

const Article = ({ title, date, link, image }) => {
	return (
		<motion.li
			initial={{ y: 200 }}
			whileInView={{ y: 0, transition: { duration: 0.5, ease: 'easeInOut' } }}
			viewport={{ once: true }}
			className='relative w-full px-4 py-6 my-4 rounded-xl flex items-center justify-between bg-light text-dark first:mt-0 border border-solid border-dark border-r-4 border-b-4 dark:bg-dark dark:text-light dark:border-light'
		>
			<MovingImage title={title} image={image} link={link} />
			<span className='text-primary dark:text-primaryDark font-semibold pl-4'>
				{date}
			</span>
		</motion.li>
	)
}

const FeaturedArticle = ({ title, time, image, summary, link }) => {
	return (
		<li className='col-span-1 w-full p-4 bg-light border border-solid border-dark rounded-2xl relative dark:bg-dark dark:border-light'>
			<div className='absolute top-0 -right-3	-z-10 w-[101%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl dark:bg-light' />
			<Link
				href={link}
				target='_blank'
				className='w-full inline-block cursor-pointer overflow-hidden rounded-lg'
			>
				<FramerImage
					whileHover={{ scale: 1.05 }}
					transition={{ duration: 0.2 }}
					src={image}
					alt={title}
					className='w-full h-auto'
					priority
					sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw'
				/>
			</Link>
			<Link href={link} target='_blank'>
				<h2 className='capitalize text-2xl font-bold my-2 mt-4 hover:underline'>
					{title}
				</h2>
			</Link>
			<p className='text-sm mb-2'>{summary}</p>
			<span className='text-primary dark:text-primaryDark font-semibold'>
				{time}
			</span>
		</li>
	)
}

const Articles = () => {
	return (
		<>
			<Head>
				<title>Portfolio | Articles</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main className='w-full mb-16 flex flex-col items-center justify-center overflow-hidden dark:text-light'>
				<Layout className='pt-16'>
					<AnimatedText text='Words Can Change The World!' className='mb-16' />
					<ul className='grid grid-cols-2 gap-16'>
						<FeaturedArticle
							title='Build A Custom Pagination Component In Reactjs From Scratch'
							time='9 min read'
							image=''
							summary='Learn how to build a custom pagination component in ReactJS from scratch. 
							Follow this step-by-step guide to integrate Pagination component in your ReactJS project.'
							link='/'
						/>
						<FeaturedArticle
							title='Build A Custom Pagination Component In Reactjs From Scratch'
							time='9 min read'
							image=''
							summary='Learn how to build a custom pagination component in ReactJS from scratch. 
						Follow this step-by-step guide to integrate Pagination component in your ReactJS project.'
							link='/'
						/>
					</ul>
					<h2 className='font-bold text-4xl w-full text-center my-16'>
						All Articles
					</h2>
					<ul>
						<Article
							title='Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling'
							link='/'
							date='May 23, 2023'
							image=''
						/>
						<Article
							title='Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling'
							link='/'
							date='May 23, 2023'
							image=''
						/>
						<Article
							title='Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling'
							link='/'
							date='May 23, 2023'
							image=''
						/>
						<Article
							title='Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling'
							link='/'
							date='May 23, 2023'
							image=''
						/>
						<Article
							title='Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling'
							link='/'
							date='May 23, 2023'
							image=''
						/>
					</ul>
				</Layout>
			</main>
		</>
	)
}

export default Articles
