import AnimatedText from '@/components/Animated/AnimatedText'
import HireMe from '@/components/HireMe'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/Layout'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
	return (
		<>
			<Head>
				<title>Portfolio | Home</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main className='flex items-center text-dark w-full dark:text-light 2xl'>
				<Layout className='pt-0 md:pt-16 sm:pt-8'>
					<div className='flex items-center justify-between w-full mt-16 lg:flex-col'>
						<div className='w-1/2 md:w-full'>
							{/* <Image src={avatar} alt='pruffit' className='w-full h-auto pointer-events-none'/> */}
						</div>
						<div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
							<AnimatedText
								text='Turning Vision Into Reality With Code And Design.'
								className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'
							/>
							<p className='my-4 text-base font-medium md:text-sm sm-text-xs'>
								As a skilled full-stack developer, I am dedicated to turning
								ideas into innovative web applications. Explore my latest
								projects and articles, showcasing my expertise in React.js and
								web development.
							</p>
							<div className='flex items-center self-start mt-2 lg:self-center'>
								<Link
									href='/dummy.pdf'
									target='_blank'
									className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark mr-2 transition-colors ease dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-light dark:hover:border-light md:p-2 md:px-4 md:text-base'
									download='true'
								>
									Resume <LinkArrow className='w-6 ml-1' />
								</Link>
								<Link
									href='mailto:kotlaevdanil@gmail.com'
									target='_blank'
									className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark transition-colors ease dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-light dark:hover:border-light md:p-2 md:px-4 md:text-base'
								>
									Contact <LinkArrow className='w-6 ml-1' />
								</Link>
							</div>
						</div>
					</div>
				</Layout>
				<HireMe />
			</main>
		</>
	)
}
